version: "3.0"
services:
    mysql:
        image: mysql:5.7
        volumes:
            - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
            - ./mysql/data:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - 8889:3306
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - app-network
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
        ports:
            - 3001:80
        networks:
            - app-network
    php:
        depends_on:
            - mysql
        build:
            dockerfile: Dockerfile
            context: "php"
            args:
                - PHP_BASE_IMAGE_VERSION
                - X_LEGACY_GD_LIB
                - PECL_XDEBUG_INSTALL_SUFFIX
                - PECL_MONGODB_INSTALL_SUFFIX
        environment:
            - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
            - PHP_ENABLE_XDEBUG=1
            - TEST_RUNTIME_PATH=/tmp/runtime
        volumes:
            - ./app/:/app:delegated
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
        ports:
            - "80:80"
        networks:
            - app-network
networks:
    app-network:
        driver: bridge